bootstrap-version: 4.5.3
assets:
  js:
    - /assets/js/startup.js
    - /node_modules/js-cookie/src/js.cookie.js
    - /themes/front-end/{{frontEndTheme}}/js/01.cookie-consent-util.js
    - /themes/front-end/{{frontEndTheme}}/js/02.1.cookie-consent-themes.js
    - /themes/front-end/{{frontEndTheme}}/js/02.2.cookie-consent-custom-css.js
    - /themes/front-end/{{frontEndTheme}}/js/02.3.cookie-consent-informational.js
    - /themes/front-end/{{frontEndTheme}}/js/02.4.cookie-consent-opt-out.js
    - /themes/front-end/{{frontEndTheme}}/js/02.5.cookie-consent-opt-in.js
    - /themes/front-end/{{frontEndTheme}}/js/02.6.cookie-consent-location.js
    - /themes/front-end/{{frontEndTheme}}/js/card.js
    - /themes/front-end/{{frontEndTheme}}/js/counterup2.js
    - /themes/front-end/{{frontEndTheme}}/js/index.js
    - /themes/front-end/{{frontEndTheme}}/js/noframework.waypoints.js
    - /themes/front-end/{{frontEndTheme}}/js/odometer.min.js
    - /themes/front-end/{{frontEndTheme}}/js/prism.js
    - /themes/front-end/{{frontEndTheme}}/js/simplebar.js
    - /themes/front-end/{{frontEndTheme}}/js/swiper.js
    - /themes/front-end/{{frontEndTheme}}/js/popper.js
    - /themes/front-end/{{frontEndTheme}}/js/jquery.js
    - /themes/front-end/{{frontEndTheme}}/js/jquery.easing.min.js
    - /themes/front-end/{{frontEndTheme}}/js/jquery.validate.js
    - /themes/front-end/{{frontEndTheme}}/js/jquery.smartWizard.js
    - /themes/front-end/{{frontEndTheme}}/js/plugins/jquery.animatebar.js
    - /themes/front-end/{{frontEndTheme}}/js/feather.min.js
    - /themes/front-end/{{frontEndTheme}}/js/bootstrap.js
    - /themes/front-end/{{frontEndTheme}}/js/aos.js
    - /themes/front-end/{{frontEndTheme}}/js/typed.js
    - /themes/front-end/{{frontEndTheme}}/js/jquery.magnific-popup.js
    - /themes/front-end/{{frontEndTheme}}/js/cookieconsent.min.js
    - /themes/front-end/{{frontEndTheme}}/js/common-script.js
    - /themes/front-end/{{frontEndTheme}}/js/forms.js
    - /themes/front-end/{{frontEndTheme}}/js/stripe-bubbles.js
    - /themes/front-end/{{frontEndTheme}}/js/stripe-menu.js
    - /themes/front-end/{{frontEndTheme}}/js/cc.js
    - /themes/front-end/{{frontEndTheme}}/js/pricing.js
    - /themes/front-end/{{frontEndTheme}}/js/shop.js
    - /themes/front-end/{{frontEndTheme}}/js/svg.js
    - /themes/front-end/{{frontEndTheme}}/js/site.js
    - /themes/front-end/{{frontEndTheme}}/js/site-custom.js
    - /themes/front-end/{{frontEndTheme}}/js/03.demo.js
    - /node_modules/ace-builds/src-min-noconflict/ace.js
    - /node_modules/ace-builds/src-min-noconflict/ext-beautify.js
    - /node_modules/axios/dist/axios.min.js
    - /node_modules/jsoneditor/dist/jsoneditor.min.js
    - /node_modules/formiojs/dist/formio.full.min.js
    - /node_modules/@fancyapps/fancybox/dist/jquery.fancybox.min.js
    - /node_modules/dropzone/dist/min/dropzone.min.js
    - /node_modules/video.js/dist/video.min.js
    - /assets/js/common.js
    - /sonicjs-services/shared.service.js
    - /sonicjs-services/global.service.js
    - /sonicjs-services/helper.service.js
    - /sonicjs-services/formatting.service.js
    - /sonicjs-services/data.service.js
    - /sonicjs-services/form.service.js
    - /page-builder/js/page-builder.js:
        isPageBuilder: true
  css:
    - /themes/front-end/{{frontEndTheme}}/css/template-processed.css
    - /themes/front-end/{{frontEndTheme}}/css/all.css
    - /themes/front-end/{{frontEndTheme}}/css/aos.css
    - /themes/front-end/{{frontEndTheme}}/css/cookieconsent.min.css
    - /themes/front-end/{{frontEndTheme}}/css/magnific-popup.css
    - /themes/front-end/{{frontEndTheme}}/css/odometer-theme-minimal.css
    - /themes/front-end/{{frontEndTheme}}/css/prism-okaidia.css
    - /themes/front-end/{{frontEndTheme}}/css/smart_wizard.css
    - /themes/front-end/{{frontEndTheme}}/css/smart_wizard_theme_arrows.css
    - /themes/front-end/{{frontEndTheme}}/css/smart_wizard_theme_circles.css
    - /themes/front-end/{{frontEndTheme}}/css/smart_wizard_theme_dots.css
    - /themes/front-end/{{frontEndTheme}}/css/swiper.css
    - /themes/front-end/{{frontEndTheme}}/css/theme.css
    - /node_modules/@fancyapps/fancybox/dist/jquery.fancybox.min.css
    - /node_modules/formiojs/dist/formio.form.min.css
    - /node_modules/jsoneditor/dist/jsoneditor.min.css
    - /assets/css/common.css
    - /node_modules/video.js/dist/video-js.min.css
